### ISSUE TITLE
Won´t get anything from luckyblock

### ISSUE THREAD

**Issue by Ansaen** [I2000C/NewAmazingLuckyBlocks#11]
when i break a lucky block the only think i get is sponge .

**Comment by I2000C** [comment]
What Minecraft version are you using?

**Comment by I2000C** [comment]
Have you added some worlds in the "config.yml" file?

**Comment by Ansaen** [comment]
no, i didnt

ne 29. 9. 2019 o 18:48 I2000C <notifications@github.com> napísal(a):

**Comment by I2000C** [comment]
Then, add some worlds in the config.yml file. In the plugin webpage, there is a section called "HOW TO ADD WORLDS", that could help you

**Comment by Ansaen** [comment]
Ok thanks for advice

Dňa po 30. 9. 2019, 22:46 I2000C <notifications@github.com> napísal(a):

**Comment by I2000C** [comment]
If this solved your problem, I'll close this issue
