### ISSUE TITLE
List of Enchantments

### ISSUE THREAD

**Issue by blockswerker** [I2000C/NewAmazingLuckyBlocks#14]
I've been able to figure out all the item names, but what enchantments can be applied to items as rewards?

**Comment by I2000C** [comment]
Here you will find the enchantment list of Minecraft 1.17:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
However, instead of adding enchantments manually, you can use the /alb menu command to manage packs, outcomes and rewards.
