### ISSUE TITLE
More type of LuckyBlocks.

### ISSUE THREAD

**Issue by IDefalt76** [I2000C/NewAmazingLuckyBlocks#16]
Hi everyone,
I have a questions, is it possible create more types of LuckyBlock? (For example LuckyBlock and LuckyBlockVip).
Thanks.

**Comment by I2000C** [comment]
Hi, do you mean being able to create LuckyBlock types so that you can choose the material (or head texture) and the possible outcomes of each type?

**Comment by IDefalt76** [comment]
Yes, for example you can create a luckyblock that is for normal users and have as material the sponge, and you can create another type of luckyblock that is for vip users and have as material the wet sponge. And they will give different outcomes.

**Comment by I2000C** [comment]
Interesting 😃 
Besides, each type could have a custom crafting recipe and permissions.
I will add this feature, but will have to wait since I'm very busy these days.

**Comment by IDefalt76** [comment]
Ok perfect, thank you for listening...i'll wait the update!

**Comment by namzz1326** [comment]
i need a 1.19 support please :c

**Comment by I2000C** [comment]
The latest plugin build already supports Minecraft 1.19.
However, I want to write some additional documentation (Wiki) before releasing it.

If you want to test it anyway, you can compile it from source (development branch) or use the **jar** inside this file
[NewAmazingLuckyBlocks-3.0.0-PRE_RELEASE.zip](https://github.com/I2000C/NewAmazingLuckyBlocks/files/9152182/NewAmazingLuckyBlocks-3.0.0-PRE_RELEASE.zip)

**Comment by I2000C** [comment]
Feature added in latest update (3.0.0_34)
