### ISSUE TITLE
Outcome packs not showing in game

### ISSUE THREAD

**Issue by KindaNeatdoe** [I2000C/NewAmazingLuckyBlocks#17]
MC version: 1.19
Plugin version: 3.0.0_34

Packs are there in folder , but dont show up in outcome pack menu or luckyblock menu.

![Screen Shot 2022-08-08 at 11 34 18 AM](https://user-images.githubusercontent.com/75075102/183350183-ea956c57-8990-477f-9c8a-f7fa0abae3a9.png)
![Screen Shot 2022-08-08 at 11 34 42 AM](https://user-images.githubusercontent.com/75075102/183350195-e1435fdd-9f51-4637-bc32-5ad419a24633.png)
<img width="977" alt="Screen Shot 2022-08-08 at 11 34 58 AM" src="https://user-images.githubusercontent.com/75075102/183350197-26f7ef45-3050-4d0e-8a6b-b8148ac2480b.png">
<img width="897" alt="Screen Shot 2022-08-08 at 11 35 03 AM" src="https://user-images.githubusercontent.com/75075102/183350201-6f233cc7-1f68-44f5-aef0-bce4eef443a0.png">
<img width="772" alt="Screen Shot 2022-08-08 at 11 35 08 AM" src="https://user-images.githubusercontent.com/75075102/183350205-0d7b25eb-72ed-4f5e-b8a7-e233d719f6ec.png">

EDIT: Some more info: These error messages happen in console chat:

! [Mon 05:28:26 WARN  Minecraft] [NewAmazingLuckyBlocks] LuckyBlockType "default" doesn't contain any valid outcome pack
! [Mon 05:28:26 WARN  Minecraft] [NewAmazingLuckyBlocks] LuckyBlockType "default2" doesn't contain any valid outcome pack
! [Mon 05:28:26 WARN  Minecraft] [NewAmazingLuckyBlocks] LuckyBlockType "other" doesn't contain any valid outcome pack

! [Mon 05:33:11 WARN  Minecraft] [NewAmazingLuckyBlocks] Total probability of LuckyBlockType "default" must be positive
! [Mon 05:33:15 WARN  Minecraft] [NewAmazingLuckyBlocks] Total probability of LuckyBlockType "default2" must be positive
! [Mon 05:33:24 WARN  Minecraft] [NewAmazingLuckyBlocks] Total probability of LuckyBlockType "default" must be positive
! [Mon 05:33:30 WARN  Minecraft] [NewAmazingLuckyBlocks] Total probability of LuckyBlockType "other" must be positive

**Comment by I2000C** [comment]
That is so strange, I will take a look at it

**Comment by I2000C** [comment]
What OS are you using?

**Comment by KindaNeatdoe** [comment]
Server is running on Linux, and client is macos. Bug is fixed I just had to delete the jar and put it in again

**Comment by I2000C** [comment]
Ok, then I will mark this issue as closed.
