### ISSUE TITLE
Feature request: Command syntax

### ISSUE THREAD

**Issue by SlimeDog** [I2000C/NewAmazingLuckyBlocks#5]
NALB 1.3.5

Briefly, NALB command syntax included the ability to give lucky blocks to a specified player. Tab-completion was also supported. The current version includes neither of those features. Please return them.

**Comment by I2000C** [comment]
Then do you want the option of giving wands, objects and LuckyBlocks to any specified player. I will return it in the next update.

**Comment by SlimeDog** [comment]
I don't care about the objects other than lucky blocks, but others may. It makes sense to support them all.
