### ISSUE TITLE
Add custom player head support

### ISSUE THREAD

**Issue by I2000C** [I2000C/NewAmazingLuckyBlocks#8]
In order to add custom player head support it is needed to:

- **Detect the texture/HeadID of that block and compare with a previous saved texture/HeadID (BlockBreakEvent)**
- **Set the texture/HeadID of a concrete block ("/alb randomblock" command)**
- Give a custom textured head block to a concrete player ("/alb give luckyblock") (NO problems with this)

**Comment by axemwa** [comment]
Maybe ask DeluxeMenus author clip for some tips? They have been using hdb heads compatibility for a while now for their plugin so they may be able to help :) 

Plugin - https://www.spigotmc.org/resources/deluxemenus.11734/
Author - https://www.spigotmc.org/resources/authors/clip.1001/

**Comment by I2000C** [comment]
Thanks, but the problem is with solid blocks, not with inventory block items.
I have used hdb heads and it works fine for giving the "lucky block" item with custom head texture to any player.
The problem is how to use it to replace solid head blocks texture. Also I have asked Arcaniax, the author of hdb, for help. However he has told me that to do that it's necessary to modify Minecraft code.
Nevertheless I believe there has to be another way, for now I will continue investigating.
If you find any solution, don't hesitate to tell me it.

**Comment by axemwa** [comment]
would this help?
https://www.spigotmc.org/resources/gravy.45288/
in this plugin player heads (with their skins) are spawned above graves when they die and I'm certain you can pick them up too, author may be able to help sorry if this isn't helpful...
hmm it is tricky to think as to how you could implement this.

SuperLuckyBlock plugin uses a player skin as the lucky block (using player names) which is placeable as an item/block, maybe you could ask them how they did it and use the same method, but for hdb tho if that makes sense
https://www.spigotmc.org/resources/superluckyblock-1-8-1-13-the-luckyblock-plugin-that-gives-you-full-control.48837/

I'm sure they won't mind a bit of competition lol

**Comment by axemwa** [comment]
Paper devs might know of another way
Here's their discord, they usually pretty quick to reply :)
https://discord.gg/jETyjUw

**Comment by I2000C** [comment]
Ok, I will take a look

**Comment by axemwa** [comment]
Just to clarify are u trying to get the textures for headblocks to show when they are placed or are you trying to get headblock textures onto full solid blocks (like how the resourcepack replaces the sponge)?

**Comment by I2000C** [comment]
The first one: get the textures and place the head blocks with these textures

**Comment by axemwa** [comment]
Oh well it should definately be possible without having to alter minefcraft code itself, surely

**Comment by I2000C** [comment]
I have discovered a way to place custom head blocks with HeadDatabaseAPI based textures. So, there is only one thing left: How to detect custom head blocks that have custom textures. I have think this could be done by comparing the block that you break with the head from the api that you have selected (i.e. by its ID in the config). The only problem here is that you break a **block** and the head from the api is an **item stack**.
Also, if you are thinking in other ways to do it, tell me then

**Comment by axemwa** [comment]
Hmm I'm not sure... soz im not very smart with these things, did u get any tips from SuperLuckyBlocks plugin author (https://www.spigotmc.org/resources/superluckyblock-1-8-1-13-the-luckyblock-plugin-that-gives-you-full-control.48837/) about what methods they used? (they using heads from player name not from a database so it might work different but it might be worth asking)

**Comment by axemwa** [comment]
This author just added HDB integration for their luckyblock plugin on spigot so I'm sure you can ask them for some pointers
![image](https://user-images.githubusercontent.com/37608633/51792711-1c826800-2205-11e9-946f-b6d8feac7a7f.png)

**Comment by I2000C** [comment]
Yes, I think so. I will ask him for some tips in order to solve the issue

**Comment by I2000C** [comment]
I have asked him and the answer is that he doesn't know how to do it (what it's so strange due to he may has something similar in his lucky block plugin). However, I will research other methods

**Comment by axemwa** [comment]
that is strange, ok good luck

edit - He probably doesn't want any competition since yours is free and his isn't, cause he literally just added the feature not long ago lol

**Comment by I2000C** [comment]
Yes, you are right

**Comment by axemwa** [comment]
For the resourcepack method Isn't there a way where u can use the resourcepack to apply the luckyblock skin onto an item that has a set durability so that it doesn't replace the item itself ingame cause that item doesn't normall have durability?
eg: 
SPONGE that has durability of %10 uses custom Lucky_Block texture
SPONGE found in game uses its default texture since it has no durability setting

**Comment by I2000C** [comment]
Interesting, but is it possible to set block durability? I think this can be only done with items

**Comment by axemwa** [comment]
Aren't playerheads/luckyblocks items though or do u mean for when it's placed? Sorry if that reply was silly not thinking clearly atm not feelin well

**Comment by I2000C** [comment]
I don't understand exactly what do you mean

**Comment by axemwa** [comment]
nvm if the durability thing wont work all g was just a thought

**Comment by I2000C** [comment]
What is "nvm"?

**Comment by axemwa** [comment]
It means NeVer Mind

**Comment by I2000C** [comment]
Ok

**Comment by I2000C** [comment]
After many hours of research, there is only one small thing that gives problems.
When you use the command "/alb give luckyblock" with the Head Mode that I have included, it gives you a certain head whose ID you can specify in the config. Then, if you place that head and you break it, the event works correctly. Moreover, if you break other head with different ID, the event won't occur.
Up to here, all right.
The real problem is when you use the command "/alb randomblock". Apparently the blocks that have been placed have the texture of the head that you have specified. However, if you break them, absolutely nothing will happen.
After searching and looking for the cause, I noticed that the ItemStacks were different (the ItemStack of the block that you get with the command "/alb give luckyblock" and the ItemStack that you get when you break a block placed with the command "/alb randomblock"). Their texture is the same, but for some reason they are recognized as different stacks (You can check that by breaking them in survival mode).

Here I attach a copy of the plugin so that you can observe the issue of which I am talking about.

[NewAmazingLuckyBlocks(CustomHeadBlockIssue).zip](https://github.com/I2000C/NewAmazingLuckyBlocks/files/2849166/NewAmazingLuckyBlocks.CustomHeadBlockIssue.zip)

**Comment by axemwa** [comment]
I see, hmm sorry not much else I can do to help as I am pretty new to server development myself so as far as coding goes this is too advanced for me sorry. If only the other author who managed to do it would help you out. I have a copy of his plugin/jar that I bought would you like to have a look over his code if i send it to you to see what methods he used or is that illegal just to look at the code?

**Comment by I2000C** [comment]
I believe that if I only see the code to know how to solve this issue it wouldn't be illegal

**Comment by axemwa** [comment]
thats wat i thought, in that case PM me on discord and I'll send u the jar to look at :)
my username for discord is Shano_dekono#5776
